apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: exampleproject
  name: exampleproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exampleproject
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: exampleproject
    spec:
      containers:
        - image: polsoftex.azurecr.io/exampleproject:latest
          name: exampleproject
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: exampleproject
  name: exampleproject
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: exampleproject
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: aks-helloworld
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: exampleproject.polcluster-dns-799051be.hcp.eastus.azmk8s.io
      http:
        paths:
          - backend:
              serviceName: aks-helloworld
              servicePort: 80
            path: /