name: Deploy

env:
  imageName: "example"
  imageRegistry: "zdrowejedzeniecontainerregistry.azurecr.io"

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ imageRegistry }}
          username: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}

      - name: Build and push image to registry
      - run: |
          docker build . -t ${{ imageRegistry }}/${{ imageName }}:latest
          docker push ${{ imageRegistry }}/${{ imageName }}:latest

      #TODO DEPLOYMENT