name: Deploy

env:
  imageName: "example"

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Log in to Azure CR'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        
        - name: 'Build and push image'
          run: |
            chmod +x gradlew
            ./gradlew bootBuildImage --imageName "${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.imageName }}:latest"
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.imageName }}:latest

