name: Test

on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
# TEST
      - run: |
          chmod +x ./gradlew
          ./gradlew test
# TEST